//
// Created by gaburolo on 30/08/18.
//

#ifndef BUSQUEDASECUENCIAL_BUSQUEDABINARIA_H
#define BUSQUEDASECUENCIAL_BUSQUEDABINARIA_H


class busquedaBinaria {

};


#endif //BUSQUEDASECUENCIAL_BUSQUEDABINARIA_H
